version: '3.8'

services:
  gateway_service:
    build: ./gateway_service
    ports:
      - "8000:8000"
    depends_on:
      - menu_service
      - user_service

  menu_service:
    build: ./menu_service
    ports:
      - "8001:8001"

  user_service:
    build: ./user_service
    ports:
      - "8002:8002"