version: '3.8'

services:
  gateway_service:
    build: ./gateway_service
    ports:
      - "8000:8000"
    depends_on:
      - menu_service
      - user_service

  menu_service:
    build: ./menu_service
    ports:
      - "8001:8001"

  user_service:
    build: ./user_service
    ports:
      - "8002:8002"

  tests:
    image: python:3.9-slim
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - gateway_service
      - menu_service
      - user_service
    command: >
      sh -c "pip install pytest requests &&
             pytest gateway_service/tests/ &&
             pytest menu_service/tests/ &&
             pytest user_service/tests/"